name: backend-continuous-integration

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: 3.11

jobs:
  lint:
    name: Run lint backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup python environment
        uses: actions/setup-python@v4
        with:
          python-version: ${{env.PYTHON_VERSION}}
      
      - name: Install pipenv
        run: |
          pip install pipenv
      
      - name: Install dependencies
        run: |
          pipenv install
      
      - name: Run lint
        run: |
          pipenv run lint
  
  test: 
    name: Run test backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./stater/backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup python environment
        uses: actions/setup-python@v4
        with:
          python-version: ${{env.PYTHON_VERSION}}
      
      - name: Install pipenv
        run: |
          pip install pipenv
      
      - name: Install dependencies
        run: |
          pipenv install 
      
      - name: Run test
        run: | 
          pipenv run test